spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_SECRET}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

clients:
  clerk:
    api-key: ${CLERK_API_KEY}
    jwt-issuer: ${CLERK_JWT_ISSUER}
  stripe:
    api-key: ${STRIPE_API_KEY}
    monthly-price-ids:
      PRO: ${STRIPE_MONTHLY_PRICE_ID_PRO}
      PREMIUM: ${STRIPE_MONTHLY_PRICE_ID_PREMIUM}
