spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_SECRET}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: ${DATABASE_FLYWAY_ENABLED:false}
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
      database: 0
      timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  jackson:
    default-property-inclusion: non_null

ui:
  base-url: ${UI_BASE_URL}

clerk:
  api-key: ${CLERK_API_KEY}
  jwt-issuer: ${CLERK_JWT_ISSUER}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  success-url: ${ui.base-url}/account
  cancel-url: ${ui.base-url}/account/cancel
  return-url: ${ui.base-url}/account
  pro-product-id: ${STRIPE_PRO_PRODUCT_ID}
  premium-product-id: ${STRIPE_PREMIUM_PRODUCT_ID}
  pro-monthly-price-id: ${STRIPE_PRO_MONTHLY_PRICE_ID}
  pro-yearly-price-id: ${STRIPE_PRO_YEARLY_PRICE_ID}
  premium-monthly-price-id: ${STRIPE_PREMIUM_MONTHLY_PRICE_ID}
  premium-yearly-price-id: ${STRIPE_PREMIUM_YEARLY_PRICE_ID}

r2:
  endpoint: ${R2_ENDPOINT}
  access-key: ${R2_ACCESS_KEY}
  secret-key: ${R2_SECRET_KEY}
  bucket-name: ${R2_BUCKET_NAME}
  region: ${R2_REGION:auto}
  public-domain: ${R2_PUBLIC_DOMAIN}
